# Global defaults for https://github.com/jdx/mise
# 1. copy to ~/.config/mise
# 2. mise install
# 3. mise tasks run finit

[settings]

idiomatic_version_file_enable_tools = ['node']


[tools]
## languges/sdks
node = "20.11.1"

java = "17"
scala = "2.13.12"

erlang = "26"
elixir = "1.16.1-otp-26"

## cli
# better "cd"
zoxide = "latest"
fzf = "latest"
gum = "latest"

## git
git = "latest"
github-cli = "latest"


## containers
colima = "latest"
# also do https://github.com/abiosoft/colima/issues/365#issuecomment-1333124133
# alternatives:
# lima
# colima - OSS
  # FAQ helped get past socket issues, https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
  # works with "brew install docker"
# podman - OSS
  # install podman CLI (via browser -> app install, or brew install podman)
  # or, install podman desktop (via browser -> app install)
  # alias docker to podman
    # "brew install docker-compose" works too; "executing external compose provider docker-compose". Even "podman compose" hands over to docker compose.
  # so far minor issues like needing docker-credential-helper, https://github.com/docker/for-mac/issues/2131#issuecomment-343712703
  # cleanup notes https://github.com/containers/podman/issues/11319
# rancher desktop - ... not tried yet ... 
# portainer - not drop-in replacement for docker; requires docker (https://docs.portainer.io/start/install-ce/server/docker/linux)
# orbstack - $8/m enterprise, free personal, some OSS components
# docker desktop - $5/m; "brew install docker" isn't enough due to missing daemon. heavy too
# dockstation - not OSS, not updated for 3 years
k9s = "latest"

[tasks.finit]
run = [
  "gum confirm 'Set Colima socket to zshrc?' && echo 'export DOCKER_HOST=$HOME/.colima/docker.sock' >> ~/.zshrc",
  "gum confirm 'Open zoxide readme to finish install?' && open https://github.com/ajeetdsouza/zoxide?tab=readme-ov-file#installation",
]

[settings]
disable_tools = ["mill"] # ignore .mill-version; prefer millw
experimental = true
